services:
  - docker

before_install:
  - docker build -t fidelisclayton/docker-react-tutorial -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fidelisclayton/docker-react-tutorial npm test

after_success:
  - docker build -t fidelisclayton/multi-client ./client
  - docker build -t fidelisclayton/multi-nginx ./nginx
  - docker build -t fidelisclayton/multi-server ./server
  - docker build -t fidelisclayton/multi-worker ./worker
  # Log in Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker hub
  - docker push fidelisclayton/multi-client
  - docker push fidelisclayton/multi-nginx
  - docker push fidelisclayton/multi-server
  - docker push fidelisclayton/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-173256646796
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
